# Convert team id (api) to team id (DB)
# Example:
# > t_teamName2id("nba.t.1")
# [1] "atl"
t_teamName2id <- function(teamName){
  teamId <- switch(teamName,
                   "nba.t.1"  = "atl",
                   "nba.t.2"  = "bos",
                   "nba.t.3"  = "nor",
                   "nba.t.4"  = "chi",
                   "nba.t.5"  = "cle",
                   "nba.t.6"  = "dal",
                   "nba.t.7"  = "den",
                   "nba.t.8"  = "det",
                   "nba.t.9"  = "gsw",
                   "nba.t.10" = "hou",
                   "nba.t.11" = "ind",
                   "nba.t.12" = "lac",
                   "nba.t.13" = "lal",
                   "nba.t.14" = "mia",
                   "nba.t.15" = "mil",
                   "nba.t.16" = "min",
                   "nba.t.17" = "bro",
                   "nba.t.18" = "nyk",
                   "nba.t.19" = "orl",
                   "nba.t.20" = "phi",
                   "nba.t.21" = "pho",
                   "nba.t.22" = "por",
                   "nba.t.23" = "sac",
                   "nba.t.24" = "sas",
                   "nba.t.25" = "okc",
                   "nba.t.26" = "uth",
                   "nba.t.27" = "was",
                   "nba.t.28" = "tor",
                   "nba.t.29" = "mem",
                   "nba.t.30" = "cha"
                   # "Toronto"      = "tor",
                   # "Boston"       = "bos",
                   # "Brooklyn"     = "bro",
                   # "New York"     = "nyk",
                   # "Philadelphia" = "phi",
                   # "Chicago"      = "chi",
                   # "Cleveland"    = "cle",
                   # "Detroit"      = "det",
                   # "Indiana"      = "ind",
                   # "Milwaukee"    = "mil",
                   # "Atlanta"      = "atl",
                   # "Charlotte"    = "cha",
                   # "Miami"        = "mia",
                   # "Orlando"      = "orl",
                   # "Washington"   = "was",
                   # "LA Clippers"  = "lac",
                   # "LA Lakers"    = "lal",
                   # "Phoenix"      = "pho",
                   # "Sacramento"   = "sac",
                   # "Golden State" = "gsw",
                   # "New Orleans"  = "nor",
                   # "Houston"      = "hou",
                   # "Memphis"      = "mem",
                   # "San Antonio"  = "sas",
                   # "Dallas"       = "dal",
                   # "Denver"       = "den",
                   # "Minnesota"    = "min",
                   # "Oklahoma City"= "okc",
                   # "Portland"     = "por",
                   # "Utah"         = "uth"
  )
  return(teamId)
}



